// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.13.0
// source: IpMac.proto

package talon

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IpMacMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpAddress  *string `protobuf:"bytes,1,opt,name=ipAddress" json:"ipAddress,omitempty"`   // device IP address
	MacAddress *string `protobuf:"bytes,2,opt,name=macAddress" json:"macAddress,omitempty"` // device MAC address
	Timestamp  *int64  `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`  // the timestamp of the ipAddress and macAddress association
}

func (x *IpMacMsg) Reset() {
	*x = IpMacMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IpMac_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpMacMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpMacMsg) ProtoMessage() {}

func (x *IpMacMsg) ProtoReflect() protoreflect.Message {
	mi := &file_IpMac_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpMacMsg.ProtoReflect.Descriptor instead.
func (*IpMacMsg) Descriptor() ([]byte, []int) {
	return file_IpMac_proto_rawDescGZIP(), []int{0}
}

func (x *IpMacMsg) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

func (x *IpMacMsg) GetMacAddress() string {
	if x != nil && x.MacAddress != nil {
		return *x.MacAddress
	}
	return ""
}

func (x *IpMacMsg) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

var File_IpMac_proto protoreflect.FileDescriptor

var file_IpMac_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x49, 0x70, 0x4d, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a,
	0x08, 0x49, 0x70, 0x4d, 0x61, 0x63, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x2c, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x61, 0x73,
	0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x42, 0x05, 0x49, 0x70, 0x4d, 0x61, 0x63, 0x5a, 0x07, 0x2e, 0x3b, 0x74, 0x61,
	0x6c, 0x6f, 0x6e,
}

var (
	file_IpMac_proto_rawDescOnce sync.Once
	file_IpMac_proto_rawDescData = file_IpMac_proto_rawDesc
)

func file_IpMac_proto_rawDescGZIP() []byte {
	file_IpMac_proto_rawDescOnce.Do(func() {
		file_IpMac_proto_rawDescData = protoimpl.X.CompressGZIP(file_IpMac_proto_rawDescData)
	})
	return file_IpMac_proto_rawDescData
}

var file_IpMac_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_IpMac_proto_goTypes = []interface{}{
	(*IpMacMsg)(nil), // 0: IpMacMsg
}
var file_IpMac_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_IpMac_proto_init() }
func file_IpMac_proto_init() {
	if File_IpMac_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_IpMac_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpMacMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_IpMac_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IpMac_proto_goTypes,
		DependencyIndexes: file_IpMac_proto_depIdxs,
		MessageInfos:      file_IpMac_proto_msgTypes,
	}.Build()
	File_IpMac_proto = out.File
	file_IpMac_proto_rawDesc = nil
	file_IpMac_proto_goTypes = nil
	file_IpMac_proto_depIdxs = nil
}
